#! /bin/sh
### BEGIN INIT INFO
# Provides:          bubba-halt
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      0
# Short-Description: Halt hook for Excito B3 platform
### END INIT INFO

. /lib/lsb/init-functions

[ -x /usr/sbin/write-magic ] || exit 0

case "$1" in
	stop)
		log_begin_msg "Setting B3 magic shutdown value"
		/usr/sbin/write-magic
		log_end_msg $?
		;;
	*)
		echo "Usage: /etc/init.d/bubba-halt {stop}" >&2
		exit 1
		;;
esac

exit 0
